source 'https://github.com/CocoaPods/Specs.git'

target 'XLEasyFoundation_Example', :exclusive => true do
  pod "XLEasyFoundation", :path => "../"
end

target 'XLEasyFoundation_Tests', :exclusive => true do
  pod "XLEasyFoundation", :path => "../"

  
end
